name: pytorch_common
channels:
  - pytorch
  - default
dependencies:
  - python=3.7.1
  - numpy==1.21.2
  - pandas==1.3.4
  - nb_conda=2.2.1
  - pip=19.2.2
  - cudatoolkit=10.1
  - pytorch=1.8.0
  - pip:
    - dask[dataframe]==2021.11.1
    - toolz==0.10.0
    - scikit-learn==1.0.1
    - scipy==1.4.1
    - ipdb==0.13.9
    - pdbpp==0.10.3
    - dill==0.3.4
    - munch==2.5.0
    - locket==0.2.0
    - bumpversion==0.6.0
